honkabuki/config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  get 'users/show'

  devise_for :users
  resources :users
  resources :posts
  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

honkabuki/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

honkabuki/app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  mount_uploader :image, ImageUploader
  
end

honkabuki/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 has_many :posts
end

honkabuki/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

honkabuki/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.page(params[:page]).per(5)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    #保存する指示が書かれているのはcreateアクションです。
     #したがって以下の1行を付け足しましょう。
      @post.user_id = current_user.id
      
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :price, :user_id, :image)
    end

    def correct_user
    post = Post.find(params[:id])
    if current_user.id != post.user.id
      redirect_to root_path
    end
  end

end

honkabuki/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
      @users = User.all
    end

    def show
      @user = User.find(params[:id])
    end
end

honkabuki/app/helpers/application_helper.rb
module ApplicationHelper
end

honkabuki/app/helpers/posts_helper.rb
module PostsHelper
end

honkabuki/app/helpers/users_helper.rb
module UsersHelper
end

honkabuki/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Honkabuki</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p>
  <%= breadcrumbs separator: " &rsaquo; " %>
    </p>

    <header>
      <nav>
      <!-- <%= link_to 'トップ', root_path %>｜ -->
      <% if user_signed_in? %>

      Logged in as <%= current_user.email %>
      <p>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>|
      <%= link_to "ポスト一覧", posts_path %>｜
      <%= link_to 'マイページ', user_path(current_user) %>
      </p>
    <% else %>
      <%= link_to "新規登録", new_user_registration_path %> |
      <%= link_to "ログイン", new_user_session_path %>
      <% end %>
      </nav>
    </header>

    <%= yield %>
  </body>
</html>

honkabuki/app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :post_body %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :post_price %>
  </div>

  <!-- <div class="field">
    <%= form.label :user_id %><br>
　    ユーザーID
    <%= form.collection_select :user_id, User.all, :id, :id%>
  </div> -->

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

honkabuki/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

honkabuki/app/views/posts/index.html.erb
<% breadcrumb :kabuki %> <!-- これを追記 -->
<p id="notice"><%= notice %></p>

<h1>歌舞伎</h1>

<table>
  <thead>
    <tr>
      <th>picture</th>
      <th>Title</th>
      <th>Body</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <% if post.image? %>
      　<td><%=  image_tag post.image.url%></td>
      　<% else %>
      　<td>画像がありません</td>
      　<% end %>
        <td><%= link_to post.title, post_path(post)%></td>
        <td><%= post.body %></td>
        <td><%= post.price %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @posts %>
<br>

<%= link_to 'New Post', new_post_path %>

honkabuki/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

honkabuki/app/views/posts/show.html.erb
<% breadcrumb :post_user, @post %> <!-- これを追記 -->
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Price:</strong>
  <%= @post.price %>
</p>

<% if current_user.id == @post.user_id %>
  <%= link_to 'Edit', edit_post_path(@post) %> |
  <%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' } %> |
<% end %>
<%= link_to 'Back', posts_path %>

honkabuki/app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

honkabuki/app/views/users/show.html.erb
<!-- <h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p> -->
<ul>  
    <li>
      <%= link_to user_path(@user) do %>
        <div class="text">投稿数</div>
        <div class="num"><%= @user.posts.count %></div>
      <% end %>
    </li>
</ul>


<% @user.posts.each do |post| %>
    <h4 class="user">
        <span class="user-name">
          <%= link_to post.user.email, user_path(post.user) %>
        </span>
    <span class="user-id"><%= post.user.email %></span>
    </h4>
    <div class="post-body">
        <%= post.body %>
    </div>

<% end %>